workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event' && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == 'main'

stages:
  - lint
  - test

variables:
  # Use SQLite for testing
  AIRFLOW__CORE__SQL_ALCHEMY_CONN: sqlite:////tmp/airflow.db
  AIRFLOW__CORE__LOAD_EXAMPLES: "False"
  # Suppress irrelevant warnings
  PYTHONWARNINGS: "ignore::DeprecationWarning"
  # Default Airflow version
  AIRFLOW_VERSION: "3.1.5"
  PYTHON_VERSION: "3.9"

lint dags:
  stage: lint
  image: python:${PYTHON_VERSION}-slim
  before_script:
    - pip install --upgrade pip
    - pip install pylint black
  script:
    - echo "Running Black..."
    - black --check dags/
    - echo "Running Pylint..."
    - pylint --disable=import-error dags/

test dags:
  stage: test
  needs: ["lint dags"]
  image: 
    name: apache/airflow:${AIRFLOW_VERSION}-slim
    entrypoint: [""]
  before_script:
    - pip install --upgrade pip
    - pip install --user -r requirements.txt
    - export AIRFLOW_HOME=$(pwd)
    - airflow db migrate
  script:
    - pytest tests/
  cache:
    paths:
      - .pip-cache/
    key: "$CI_PROJECT_ID"
