name: CI

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'README.md'

env:
  AIRFLOW_VERSION: "3.1.5"
  PYTHON_VERSION: "3.9"

jobs:
  lint:
    name: Lint Dags
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install pylint black

      - name: Run Black
        run: |
          echo "Running Black..."
          black --check dags/

      - name: Run Pylint
        run: |
          echo "Running Pylint..."
          pylint --disable=import-error dags/

  test:
    name: Test Dags
    needs: lint
    runs-on: self-hosted
    env:
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: sqlite:////tmp/airflow.db
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"
      PYTHONWARNINGS: "ignore::DeprecationWarning"
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies and Run Tests
        run: |
          python -m pip install --upgrade pip
          python -m pip install apache-airflow==${{ env.AIRFLOW_VERSION }} --constraint "https://raw.githubusercontent.com/apache/airflow/constraints-${{ env.AIRFLOW_VERSION }}/constraints-${{ env.PYTHON_VERSION }}.txt" || python -m pip install apache-airflow==${{ env.AIRFLOW_VERSION }}
          python -m pip install -r requirements.txt
          
          # Set AIRFLOW_HOME to current workspace
          export AIRFLOW_HOME=$(pwd)
          
          # Initialize DB
          echo "Initializing DB..."
          airflow db migrate
          
          echo "Running Tests..."
          pytest tests/
